### ISSUE TITLE
What is the library about ? 

### ISSUE THREAD

**Issue by Aryaman-chandra** [sinianluoye/manim-algorithm#1]
### Issue 
Currently i have no idea how to use the library as there is no documentation and looking at source code i feel there aren't many algorithms in library too  and i am not entirely sure on the objective , whether it is the data structures or a provision for classic algorithms.

### Background 
I am actually a beginner to manim , and im learning manim to practice algorithmic problems from leetcode , cses  and etc.
I wanted to preserve my knowledge by making quick animations  to give myself quick reminders to my problems 

### Solutions 
I'd like to connect and contribute to the library to ease the work of making algorithmic explanations.

**Comment by sinianluoye** [comment]
This library is currently in the internal development stage, trying some encapsulations to better allow Manim to display algorithms and data structures, such as linked lists/arrays/binary trees, etc. In fact, I didn't plan to make this project public in the short term until it reached a certain scale, but it seems that the Manim community's spider found it. If you have any requests or suggestions to this project, welcome to leave message.
